### ISSUE TITLE
[UPDATE] Deliveroo clone with Next.js, GraphQL, Strapi and Stripe - Setup (1/7)

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#723] opened 2022-03-14 23:34 UTC
Hello 👋

This [article](https://strapi.io/blog/strapi-next-setup) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by PaulBratslavsky** [comment] 2022-07-21 18:49
I think we definitely need more GraphQl articles. So this updated will be great.  Anyone want to take this on let me know, I can also help answer any GraphQl related questions in Strapi v4 you may have.

**Comment by vcoisne** [comment] 2022-11-17 06:14
@PaulBratslavsky given how popular this one is, I wonder if we shouldn't update ourselves or highlight it on Discord or something ?

**Comment by Melanie12** [comment] 2022-11-24 10:26
Can we find and tag the original author?

**Comment by hubertnare** [comment] 2022-11-25 02:14
Hi @PaulBratslavsky , @vcoisne , and @Melanie12 .

I am willing to update this one.

**Comment by PaulBratslavsky** [comment] 2022-12-05 15:06
@vcoisne @Melanie12 @hubertnare can take on this update if the original owner does not have the time for the update.

**Comment by PaulBratslavsky** [comment] 2022-12-21 19:52
@hubertnare going to assign this update to you.  Thank you.

**Comment by hubertnare** [comment] 2022-12-23 09:17
Sure, update en route 🚀 🚀

**Comment by hubertnare** [comment] 2023-01-04 08:27
Hi @PaulBratslavsky ,

While working on this I realized this issue is precisely the same as issue  #889 but with different titles. Instead, I intend to tackle issue #1080

**Comment by PaulBratslavsky** [comment] 2023-01-20 23:02
This seems to be a duplicate of https://github.com/strapi/community-content/issues/889 closing since the articles have been written and are awaiting review.

**Closed by PaulBratslavsky** 2023-01-20 23:02 UTC
Labels: In progress, Outdated content, v4 update
