### ISSUE TITLE
complete steps for installing strapi because am getting error

### ISSUE THREAD

**Issue by PadminiP2603** [strapi/community-content#1059] opened 2022-12-10 01:45 UTC
**My Request**

**Community vote**
👍 Upvote if you like this topic
🚀 If you can make the article/video!

Thank you.

**Comment by ranjithjupaka** [comment] 2022-12-11 10:15
i am interested in writing an article

**Comment by PadminiP2603** [comment] 2022-12-11 11:36
Yes.. Please

**Comment by ranjithjupaka** [comment] 2022-12-11 12:01
do i need to provide an outline or will you assign directly?

**Comment by PadminiP2603** [comment] 2022-12-11 12:11
Provide outline.. 
Before that i will explain my error.. 
Command line:npx create-strapi-app@latest my-projects. 
Error:Cannot find module '@sentry/hub'
I have installed nodejs and npm latest version

**Comment by ranjithjupaka** [comment] 2022-12-11 12:12
can you specify the version numbers as well

**Comment by PadminiP2603** [comment] 2022-12-11 12:13
All latest version

**Comment by ranjithjupaka** [comment] 2022-12-11 12:14
did you opted manual installation ?

**Comment by ranjithjupaka** [comment] 2022-12-11 12:55
will reproduce the error and then will share the routine here

**Comment by PadminiP2603** [comment] 2022-12-11 13:00
Thank you for helping me out..

**Comment by PaulBratslavsky** [comment] 2023-01-04 19:45
This will be more appropriate as a forum post rather than a blog post.  You can create it here https://forum.strapi.io/. Closing this issue for now since a forum post on this topic will be more appropriate.

**Closed by PaulBratslavsky** 2023-01-04 19:45 UTC
Labels: Looking for author
