### ISSUE TITLE
[UPDATE] Create a food ordering app with Strapi and Next.js (1/7)

### ISSUE THREAD

**Issue by TiaraOluwanimi** [strapi/community-content#735] opened 2022-03-14 23:59 UTC
Hello 👋

This [article](https://strapi.io/blog/nextjs-react-hooks-strapi-food-app-1) is outdated and needs to be updated.

What do you all think?
👍 Nice!
❤️ I love it!
🚀 I can help you!

Thank you.

**Comment by ShadaW11** [comment] 2022-05-20 09:52
Hello @bashidagha apologies for the delay, are you still interested in updating this article?

**Comment by ShadaW11** [comment] 2022-05-30 12:02
@bashidagha any update?

**Comment by ShadaW11** [comment] 2022-06-01 15:09
Hello @bashidagha the budget for content update is 70USD per article - in this case, the article is a series, therefore the budget is 200USD.

**Comment by ShadaW11** [comment] 2022-06-02 08:25
@bashidagha As mentioned in my email, it will not be possible to process payments in crypto. Therefore, we would not be able to work on this together. Feel free to reach out if you find another solution.

**Comment by olujerry** [comment] 2022-06-27 01:19
I will like to work on this if it's still available.

**Comment by PaulBratslavsky** [comment] 2022-06-28 03:05
@olujerry yes, i don't think anyone is working on this.  So it will be awesome if you can do it.🙂

**Comment by olujerry** [comment] 2022-06-28 08:22
Okay can I get the link to the previous article i will be working with.

**Comment by PaulBratslavsky** [comment] 2022-07-21 18:58
@olujerry I did not realize that this was a duplicate of another issue that already has an author working on it.  My apologies.  I will be closing this issue because of duplication.

**Closed by PaulBratslavsky** 2022-07-21 18:58 UTC
Labels: Looking for author, Outdated content, v4 update
