### ISSUE TITLE
Strapi GraphQL best practices [SUBMIT]

### ISSUE THREAD

**Issue by popoolatopzy** [strapi/community-content#1187] opened 2023-04-24 10:05 UTC
# Strapi GraphQL best practices
Hi 👋 
I will like to work on the topic *Strapi GraphQL best practices* here is the outline for the tutorial. 

Article outlines 
- Introduction 
- prerequisites 
- What is GraphQL
- Strapi GraphQL plugin 
- Setting up Strapi
- Creating a demo app
- Using GraphQL in the app
- Conclusion

- [ ] A Strapi Tutorial / Guide / How to article
- [ ] About Headless, CMS, javascript, open source, or jamstack
- [ ] Other, specify

**What do you all think?**
❤️ I love it!
🚀 I can help you!

Thank you for submitting your article proposal.

**Comment by dessireugarte** [comment] 2023-04-24 17:05
Hello @popoolatopzy!
Would you be interested in updating [this](https://github.com/strapi/community-content/issues/611) article instead of this new topic?

**Comment by popoolatopzy** [comment] 2023-04-25 16:54
Hi @dessireugarte,
Thank you, I have checked the article but is like someone is already working on it.

**Comment by PaulBratslavsky** [comment] 2023-04-28 21:36
@popoolatopzy thanks for asking just confirmed with the previous author that they are still working on it.

**Comment by PaulBratslavsky** [comment] 2023-04-28 21:39
Closing since it is similar to this topic https://github.com/strapi/community-content/issues/611

**Closed by PaulBratslavsky** 2023-04-28 21:39 UTC
Labels: request by author
