### ISSUE TITLE
[UPDATE OUTDATED CONTENT] in Creating a Strapi Dynamic Zone & Rendering it in your Nuxt.js App? May be even use the same project to work with REST instead of GraphQL

### ISSUE THREAD

**Issue by s3-interdev** [strapi/community-content#702] opened 2022-03-04 08:27 UTC
**Description**

**Link of the content**

**What do you all think?**
👍 Nice!
❤️ I love it!
🚀 I can help you!

**Comment by PaulBratslavsky** [comment] 2022-07-21 18:36
To ensure that we can review and publish articles promptly, we will start closing inactive issues after two weeks of inactivity.

I know it has been a while, but I just wanted to follow up with everyone here to see if anyone is still interested in writing this article. If not, we will be closing this issue due to inactivity.

If any one wants to take up this update, let me know.

**Comment by PaulBratslavsky** [comment] 2022-11-17 01:23
Duplicate of another issue. Closing.

**Closed by PaulBratslavsky** 2022-11-17 01:23 UTC
Labels: Looking for author, Outdated content, no recent activity
